---
# --------------------------------

- name: "Generate EC2 keypairs"
  ansible.builtin.template:
    dest: aws-ec2-keypairs.tf
    mode: "0644"
    src: hcl2/aws/ec2/keypairs.tf.j2
  delegate_to: localhost
  tags: ["ct-terragen"]

- name: "Generate Secrets Manager secrets"
  ansible.builtin.template:
    src: hcl2/aws/secmgr/secrets.tf.j2
    dest: aws-secmgr-secrets.tf
    mode: "0644"
  delegate_to: localhost
  tags: ["ct-terragen"]

# --------------------------------
...
