---
# --------------------------------

- name: "Terraform providers"
  ansible.builtin.template:
    dest: cloud-providers.tf
    mode: "0644"
    src: hcl2/cloud/providers.tf.j2
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Ansible config file"
  ansible.builtin.copy:
    dest: ansible.cfg
    mode: "0644"
    src: ansible.cfg
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Manage Ansible dirs"
  ansible.builtin.file:
    name: "{{ item.name }}"
    mode: "{{ item.mode }}"
    state: directory
  loop: "{{ terragen_ansible_dirs }}"
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Generate VPCs"
  ansible.builtin.template:
    dest: vultr-network-vpcs.tf
    mode: "0644"
    src: hcl2/vultr/network/vpcs.tf.j2
  when: vultr is defined
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Generate compute SSH keys"
  ansible.builtin.template:
    dest: vultr-compute-sshKeys.tf
    mode: "0644"
    src: hcl2/vultr/compute/sshKeys.tf.j2
  when: vultr is defined
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Generate compute startup scripts"
  ansible.builtin.template:
    dest: vultr-compute-startUpScripts.tf
    mode: "0644"
    src: hcl2/vultr/compute/startUpScripts.tf.j2
  when: vultr is defined
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Generate compute instances"
  ansible.builtin.template:
    dest: vultr-compute-instances.tf
    mode: "0644"
    src: hcl2/vultr/compute/instances.tf.j2
  when: vultr is defined
  delegate_to: localhost
  tags: [ct-terragen]

# --------------------------------
...
