---
# --------------------------------

- name: "Terraform providers"
  ansible.builtin.template:
    dest: cloud-providers.tf
    mode: "0644"
    src: hcl2/cloud/providers.tf.j2
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Ansible config file"
  ansible.builtin.copy:
    dest: ansible.cfg
    mode: "0644"
    src: ansible.cfg
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Manage Ansible dirs"
  ansible.builtin.file:
    mode: "{{ item.mode }}"
    name: "{{ item.name }}"
    state: directory
  loop: "{{ terragen_ansible_dirs }}"
  delegate_to: localhost
  tags: [ct-terragen]

- name: "Include AWS tasks"
  ansible.builtin.include_tasks:
    file: "aws.yml"
  when: aws is defined
  tags: [ct-terragen]

- name: "Include Vultr tasks"
  ansible.builtin.include_tasks:
    file: "vultr.yml"
  when: vultr is defined
  tags: [ct-terragen]

# --------------------------------
...
